src/model/LoginBean.java
package model;
//loginBean with getters and setters to acces data
public class LoginBean {

	private String username;
	private String password;

	public String getPassword() {
		return password;
	}

	public void setPassword(String newPassword) {
		password = newPassword;
	}

	public String getName() {
		return username;
	}

	public void setName(String newUsername) {
		username = newUsername;
	}
}

src/model/PostBean.java
package model;
//Post with getters and setters to acces data from the post
public class PostBean {
	private String title = null;
	private String content = null;
	private String user = null;
	private String date = null;

	public PostBean() {
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}

src/model/UserBean.java
package model;
package model;
//Userbean with getters and setters to acces user account
public class UserBean {

	private int id;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private int role;
	private String lastlogin;

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String newFirstName) {
		firstName = newFirstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String newLastName) {
		lastName = newLastName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String newPassword) {
		password = newPassword;
	}

	public String getUserName() {
		return username;
	}

	public void setUserName(String newUsername) {
		username = newUsername;
	}

	public boolean isLoggedIn() {
		return (getFirstName().isEmpty()) ? false : true;
	}

	public int getRole() {
		return role;
	}

	public int getID() {
		return id;
	}

	public void setID(int id) {
		this.id = id;
	}

	public void setRole(int role) {
		this.role = role;
	}

	public String getLastLogin() {
		return lastlogin;
	}

	public void setLastLogin(String lastlogin) {
		this.lastlogin = lastlogin;
	}
}

public class UserBean {

	private int id;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private int role;
	private String lastlogin;

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String newFirstName) {
		firstName = newFirstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String newLastName) {
		lastName = newLastName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String newPassword) {
		password = newPassword;
	}

	public String getUserName() {
		return username;
	}

	public void setUserName(String newUsername) {
		username = newUsername;
	}

	public boolean isLoggedIn() {
		return (getFirstName().isEmpty()) ? false : true;
	}

	public int getRole() {
		return role;
	}

	public int getID() {
		return id;
	}

	public void setID(int id) {
		this.id = id;
	}

	public void setRole(int role) {
		this.role = role;
	}

	public String getLastLogin() {
		return lastlogin;
	}

	public void setLastLogin(String lastlogin) {
		this.lastlogin = lastlogin;
	}
}

src/controller/AccountServlet.java
package controller;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.UserBean;
import util.UpdateDao;

@WebServlet("/account")
public class AccountServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	public AccountServlet() {
		super();
	}
	// get all get requests
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		UserBean userBean = (UserBean) request.getSession().getAttribute("userBean");
		//Check if user is logged in else go to login
		if (userBean != null) {
		request.getRequestDispatcher("./WEB-INF/account.jsp").forward(request, response);
		} else {
		request.getRequestDispatcher("./WEB-INF/login.jsp").forward(request, response);
		}
	}
	//get all POST requests
	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		UserBean userBean1 = new UserBean();
		UserBean userBean = (UserBean) request.getSession().getAttribute("userBean");
		//Check if user is logged in else go to login
		if (userBean != null) {
		try {
		//set userBean data + update session userbean
			userBean1.setID(userBean.getID());
			userBean1.setFirstName(request.getParameter("firstname"));
			userBean1.setLastName(request.getParameter("lastname"));
			userBean1.setUserName(request.getParameter("username"));

			userBean.setFirstName(request.getParameter("firstname"));
			userBean.setLastName(request.getParameter("lastname"));
			userBean.setUserName(request.getParameter("username"));

			// Create LoginDao object and validatie user information
			UpdateDao.updateUser(userBean);
			response.sendRedirect("./account");
		} catch (Exception e) {
			// Store errorMessage in the session
			request.setAttribute("errorMessage", "Failed to update");
			// Let user login again
			request.getRequestDispatcher("./account").forward(request, response);
		}
		} else {
			request.getRequestDispatcher("./WEB-INF/login.jsp").forward(request, response);
		}
	}

}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import model.LoginBean;
import model.UserBean;
import util.LoginDao;

/**
 * Servlet implementation class Servlet
 */
@WebServlet("/login")
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static Logger LOGGER = Logger.getLogger(LoginServlet.class.getName());

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		LOGGER.log(Level.INFO, "Login servlet requested (get).");

		// Forward to the login form with an empty loginBean object.
		request.getRequestDispatcher("WEB-INF/login.jsp").forward(request, response);
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		LOGGER.log(Level.INFO, "Admin servlet requested (post).");
		//Create loginBean
		LoginBean loginBean = new LoginBean();
		//Set login parameters
		loginBean.setName(request.getParameter("name"));
		loginBean.setPassword(request.getParameter("password"));
		try {
			// Create LoginDao object and validatie user information
			UserBean userBean = LoginDao.authenticateUser(loginBean);
			// Store userBean in session
			HttpSession session = ((HttpServletRequest) request).getSession(true);
			session.setAttribute("userBean", userBean);
			// Go to the homepage
			response.sendRedirect("index.jsp");

		} catch (Exception e) {
			// Store errorMessage in the session
			request.setAttribute("errorMessage", "Email or password unknown - please try again.");

			// Store loginBean in request
			request.setAttribute("loginBean", loginBean);

			// Redirect to form again.
			request.getRequestDispatcher("/WEB-INF/login.jsp").forward(request, response);
		}
	}

}

src/controller/RegisterServlet.java
package controller;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import model.UserBean;
import util.RegisterDao;

/**
 * Servlet implementation class Servlet
 */
@WebServlet("/register")
public class RegisterServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static Logger LOGGER = Logger.getLogger(LoginServlet.class.getName());

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		LOGGER.log(Level.INFO, "Register servlet requested (get).");

		// Forward to the login form with an empty loginBean object.
		request.getRequestDispatcher("WEB-INF/register.jsp").forward(request, response);
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		LOGGER.log(Level.INFO, "Register servlet requested (post).");
		//create userBean to register
		UserBean userBean = new UserBean();
		try {
			//add data from POST to userBean
			userBean.setFirstName(request.getParameter("firstname"));
			userBean.setLastName(request.getParameter("lastname"));
			userBean.setUserName(request.getParameter("username"));
			userBean.setPassword(request.getParameter("password"));
			// Create LoginDao object and validatie user information
			RegisterDao.registerUser(userBean);
			//Redirect to login page
			response.sendRedirect("./login");
		} catch (Exception e) {
			// Store errorMessage in the session
			request.setAttribute("errorMessage", "Failed to register");

			request.getRequestDispatcher("/WEB-INF/register.jsp").forward(request, response);
		}
	}

}

WebContent/WEB-INF/account.jsp
<html>
<head>
<!-- Include head links -->
<%@ include file="./jspf/head.content.jspf"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!-- Declare session userBean -->
<jsp:useBean id="userBean" class="model.UserBean" scope="session" />
</head>
<body>
	<!-- Include header -->
	<%@ include file="/WEB-INF/jspf/header.content.jspf"%>
	<!-- Show username -->
	<div class="container center">
		<h1 class="m-4">
			Account van
			<%=userBean.getUserName()%></h1>
	</div>
	<!-- Form to show user data from userBean -->
	<div class="container">
		<form id="Login" action="account" method="POST">
			<div class="form-group">
				<input type="text" name="username" class="form-control"
					id="username" placeholder="Username"
					value="<%=userBean.getUserName()%>">
			</div>
			<div class="form-group">
				<input type="text" name="firstname" class="form-control"
					id="firstname" placeholder="First name"
					value="<%=userBean.getFirstName()%>">
			</div>
			<div class="form-group">
				<input type="text" name="lastname" class="form-control"
					id="lastname" placeholder="Last name"
					value="<%=userBean.getLastName()%>">
			</div>
			<!-- Button to update user data with POST to updateServlet -->
			<button type="submit" class="btn btn-primary">Update</button>

		</form>
	</div>
	<!-- Footer -->
	<%@ include file="./jspf/footer.content.jspf"%>
</body>
</html>

WebContent/WEB-INF/admin.jsp
<html>
<head>
<!-- Include head links -->
<%@ include file="./jspf/head.content.jspf"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!-- Declare session userBean -->
<jsp:useBean id="userBean" class="model.UserBean" scope="session" />
</head>
<body>
	<!-- Include header -->
	<%@ include file="/WEB-INF/jspf/header.content.jspf"%>
	<!-- Admin panel with user data -->
	<div class="container center">
		<h1 class="m-4">Admin Panel</h1>
	</div>
	<div class="container">
		<table class="table">
		<!-- Table head -->
			<thead class="thead-light">
				<tr>
					<th scope="col">ID</th>
					<th scope="col">Username</th>
					<th scope="col">Firstname</th>
					<th scope="col">Lastname</th>
					<th scope="col">Last login</th>
					<th scope="col">Delete</th>
				</tr>
			</thead>
			<!-- Table body -->
			<tbody>
			<!-- forEach to display all users -->
				<c:forEach var="user" items="${listUsers}">
					<tr>
						<th scope="row"><c:out value="${user.ID}" /></th>
						<td><c:out value="${user.userName}" /></td>
						<td><c:out value="${user.firstName}" /></td>
						<td><c:out value="${user.lastName}" /></td>
						<td><c:out value="${user.lastLogin}" /></td>
						<!-- Delete from to POST to delteServlet -->
						<td><form method="post" id="delete" action="delete">
								<input type="hidden" name="id"
									value="<c:out value="${user.ID}" />"> <input
									class="btn btn-danger" type="submit" value="Delete">
							</form></td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
	</div>
	<!-- Add user link button -->
	<div class="container center">
		<a href="register" class="m-4 btn btn-info">Add user</a>
	</div>
	<!-- Footer -->
	<%@ include file="./jspf/footer.content.jspf"%>
</body>
</html>

WebContent/WEB-INF/create.jsp
<html>
<head>
<!-- Include head links -->
<%@ include file="./jspf/head.content.jspf"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!-- Declare session userBean -->
<jsp:useBean id="userBean" class="model.UserBean" scope="session" />
</head>
<body>
	<!-- Include header -->
	<%@ include file="/WEB-INF/jspf/header.content.jspf"%>
	<!-- Blog post title -->
	<div class="container center">
		<h1 class="m-4">Create blog post</h1>
	</div>
	<!-- Form to show user data from userBean -->
	<div class="container">
		<form id="Create" action="create" method="POST" autocomplete="off">
			<div class="form-group">
				<input type="text" name="title" class="form-control" id="title"
					placeholder="Title">
			</div>
			<div class="form-group">
				<textarea rows="4" cols="50" name="content" class="form-control" form="Create" placeholder="Content"></textarea>
			</div>
			<!-- Button to update user data with POST to createServlet -->
			<button type="submit" class="btn btn-primary">Create</button>

		</form>
	</div>
	<!-- Footer -->
	<%@ include file="./jspf/footer.content.jspf"%>
</body>
</html>

WebContent/WEB-INF/login.jsp
<html>
<head>
<!-- Include head links -->
<%@ include file="jspf/head.content.jspf"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!-- Declare session userBean -->
<jsp:useBean id="userBean" class="model.UserBean" scope="session" />
</head>
<body>
<!-- Site background -->
	<div class="login-background">
		<div class="container container-margin">
		<!-- Login form with all the data to POST loginServlet -->
			<div class="login-form">
				<div class="main-div">
					<div class="panel">
						<h2>Login</h2>
						<p>Please enter your username and password</p>
					</div>
					<form id="Login" action="login" method="POST">

						<div class="form-group">
							<input type="text" name="name" class="form-control"
								id="inputEmail" placeholder="Username">
						</div>

						<div class="form-group">

							<input type="password" name="password" class="form-control"
								id="inputPassword" placeholder="Password">
						</div>
						<button type="submit" class="btn btn-primary">Login</button>

					</form>
				</div>
			</div>
		</div>
	</div>

WebContent/WEB-INF/post.jsp
<html>
<head>
<!-- Include head links -->
<%@ include file="/WEB-INF/jspf/head.content.jspf"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!-- Declare session userBean -->
<jsp:useBean id="userBean" class="model.UserBean" scope="session" />
<link type="text/css" rel="stylesheet"
	href="/HellowWorldFromEclipse/assets/vendor/Bootstrap/css/bootstrap.min.css" />
</head>
<body>
	<!-- Include header -->
	<%@ include file="/WEB-INF/jspf/header.content.jspf"%>
	<div class="container m-5">
		<div class="row">
			<div class="col-md-8">
				<!-- forEach loop to display all posts -->
				<c:forEach var="post" items="${listPost}">
					<div class="card mb-4">
						<div class="card-body">
							<h2 class="card-title">
								<c:out value="${post.title}" />
							</h2>
							<p class="card-text">
								<c:out value="${post.content}" />
							</p>
						</div>
						<div class="card-footer text-muted">
							Door: <c:out value="${post.user}" /><br>
							Datum: <c:out value="${post.date}" />
						</div>
					</div>
				</c:forEach>
			</div>
		    <div class="col-md-4">
				<div class="card" style="width: 18rem;">
				  <img class="card-img-top" src="./assets/img/logo.png" alt="SE">
				  <div class="card-body">
				    <p class="card-text">WebBlog made by Software-Essentials. For educational purposes only.</p>
				    <a href="./create" class="btn btn-primary">Create your own post</a>
				  </div>
				</div>
		    </div>
		</div>
	</div>
	

	<!-- Footer -->
	<%@ include file="/WEB-INF/jspf/footer.content.jspf"%>
</body>
</html>

WebContent/WEB-INF/register.jsp
<html>
<head>
<!-- Include head links -->
<%@ include file="jspf/head.content.jspf"%>

<%@ taglib uri="http://java.sun.com/jsp/jstl/sql" prefix="sql"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!-- Declare session userBean -->
<jsp:useBean id="userBean" class="model.UserBean" scope="session" />
</head>
<body>
<!-- Site background -->
	<div class="login-background">
		<div class="container container-margin">
		<!-- Register form with all the data to POST registerServlet -->
			<div class="login-form">
				<div class="main-div">
					<div class="panel">
						<h2>Register</h2>
						<p>Register to the website</p>
					</div>
					<form id="Register" action="register" method="POST" autocomplete="off">

						<div class="form-group">
							<input type="text" name="username" class="form-control"
								id="username" placeholder="Username" autocomplete="off">
						</div>
						<div class="form-group">
							<input type="text" name="firstname" class="form-control"
								id="firstname" placeholder="First name" autocomplete="off">
						</div>
						<div class="form-group">
							<input type="text" name="lastname" class="form-control"
								id="lastname" placeholder="Last name" autocomplete="off">
						</div>
						<div class="form-group">

							<input type="password" name="password" class="form-control"
								id="inputPassword" placeholder="Password" autocomplete="off">
						</div>
						<button type="submit" class="btn btn-primary">Register</button>

					</form>
				</div>
			</div>
		</div>
	</div>